stages:
  - check
  - deploy

check_file:
  stage: check
  script:
    - echo "Verificando se o arquivo index.html existe..."
    - test -f public/index.html || (echo "Erro: index.html não encontrado!" && exit 1)

pages:
  stage: deploy
  script:
    - echo "Deploy para GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
