stages:
  - check
  - deploy

check:
  stage: check
  script:
    - test -f public/index.html || (echo "Arquivo index.html não encontrado!" && exit 1)

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public
  artifacts:
    paths:
      - public
  only:
    - main
